export const paths = {
  home: '/',
  login: '/login',
  signup: '/sign-up',
  artworkList: '/artwork',
  artworkPage: '/artwork/:id',
  artists: '/artists',
  artistPage: '/artists/:id',
  artConnections: '/art-connections',
  artConnectionPage: '/art-connections/:id',
  giftCards: '/gift-cards',
  about: '/about',
  cart: '/cart',
  checkout: '/checkout',
}
